// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"coreto_Quests","status":true,"description":"Add or remove a key item from the inventory and trigger a specified common event.","parameters":{}}
];
