// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"coreto_Quests","status":true,"description":"Add or remove a key item from the inventory and trigger a specified common event.","parameters":{}},
{"name":"Iavra_MZ_Localization_byNeomaStudio","status":true,"description":"Plugin para adicionar traduções ao jogo por meio de arquivo externo.\n<Iavra Localization Core>","parameters":{"Escape Code":"#{{key}}","Languages":"en, ptbr","File Path":"{lang}.json","Option Label":"Language","Language Labels":"en:English, ptbr:Portuguese","Localization Folder":"localization"}}
];
