/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require('fs');
const path = require('path');

const FRONTEND = path.resolve(__dirname, '../..');

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(FRONTEND, relativePath), 'utf8'));
}

function map(mapId) {
  return readJson(`data/Map${String(mapId).padStart(3, '0')}.json`);
}

function event(mapData, eventId, expectedName) {
  const result = mapData.events[eventId];
  expect(result).toBeDefined();
  if (expectedName) expect(result.name).toBe(expectedName);
  return result;
}

function isPluginCommand(command, pluginName, commandName, args = {}) {
  return (
    command.code === 357 && command.parameters?.[0] === pluginName && command.parameters?.[1] === commandName && Object.entries(args).every(([key, value]) => command.parameters?.[3]?.[key] === value)
  );
}

function commandIndex(page, predicate) {
  return page.list.findIndex(predicate);
}

function variablePage(eventData, variableId, variableValue) {
  const matches = eventData.pages.filter(page => page.conditions.variableValid && page.conditions.variableId === variableId && page.conditions.variableValue === variableValue);
  expect(matches).toHaveLength(1);
  return matches[0];
}

function selectedPage(eventData, variables = {}, selfSwitches = new Set()) {
  let selected = null;
  eventData.pages.forEach((page, index) => {
    const condition = page.conditions;
    if (condition.variableValid && (variables[condition.variableId] ?? 0) < condition.variableValue) return;
    if (condition.selfSwitchValid && !selfSwitches.has(`${eventData.id}:${condition.selfSwitchCh}`)) return;
    selected = { page, index };
  });
  return selected;
}

function validateGraph(quest) {
  const reachable = new Set([quest.initialState]);
  let changed = true;
  while (changed) {
    changed = false;
    for (const transition of Object.values(quest.transitions)) {
      if (transition.from.some(state => reachable.has(state)) && !reachable.has(transition.to)) {
        reachable.add(transition.to);
        changed = true;
      }
    }
  }
  for (const terminal of quest.terminalStates) {
    if (!reachable.has(terminal)) throw new Error(`terminal ${terminal} is unreachable`);
  }
  for (const objective of quest.pkd.objectives) {
    if (!reachable.has(objective.knownFrom)) throw new Error(`objective ${objective.id} visibility is unreachable`);
    if (objective.completedAt !== null && !reachable.has(objective.completedAt)) {
      throw new Error(`objective ${objective.id} completion is unreachable`);
    }
  }
  return reachable;
}

function parsePluginsConfig() {
  const source = fs.readFileSync(path.join(FRONTEND, 'js/plugins.js'), 'utf8');
  const match = source.match(/^\/\/ Generated by RPG Maker\.\n\/\/ Do not edit this file directly\.\nvar \$plugins =\n(\[[\s\S]*\]);\n?$/);
  expect(match).not.toBeNull();
  return JSON.parse(match[1]);
}

function pkdPointer(plugins, questId, taskIndex) {
  const pkd = plugins.find(plugin => plugin.name === 'PKD_SimpleQuestSystem');
  expect(pkd?.status).toBe(true);
  const quests = JSON.parse(pkd.parameters['sqsPointers:structA']).map(JSON.parse);
  const quest = quests.find(candidate => candidate.questId === questId);
  expect(quest).toBeDefined();
  const rows = JSON.parse(quest['pointsData:structA']).map(JSON.parse);
  const row = rows.find(candidate => Number(candidate['taskIndex:int']) === taskIndex);
  expect(row).toBeDefined();
  return JSON.parse(row['points:structA'])
    .map(JSON.parse)
    .map(point => ({
      mapId: Number(point['mapId:int']),
      eventId: Number(point['evId:int']),
    }));
}

describe('Reference quest state machines — Exploration and Visual Novel', () => {
  const registry = readJson('data/CoretoQuests.json');
  const system = readJson('data/System.json');
  const mapInfos = readJson('data/MapInfos.json');
  const maps = Object.fromEntries([22, 32, 39, 44, 45, 46, 49].map(id => [id, map(id)]));

  test('keeps the authorized map boundary explicit and complete', () => {
    const descendantsOf = rootId => {
      const result = [];
      const visit = parentId => {
        mapInfos.forEach((entry, id) => {
          if (entry?.parentId === parentId) {
            result.push(id);
            visit(id);
          }
        });
      };
      visit(rootId);
      return result.sort((a, b) => a - b);
    };

    expect(descendantsOf(16)).toEqual([22, 32, 39, 44, 45]);
    expect(descendantsOf(18)).toEqual([46, 49]);
    expect(mapInfos[16].name).toBe('Exploration');
    expect(mapInfos[18].name).toBe('Visual Novel');
    expect(maps[22].note).toBe('<CoretoMapType:EX>');
    expect(maps[45].note).toBe('<CoretoMapType:EX>');
    expect(maps[46].note).toBe('<CoretoMapType:VN>');
    expect(maps[49].note).toBe('<CoretoMapType:VN>');
  });

  test('keeps both canonical graphs reachable with named, sparse milestones', () => {
    const night = registry.quests['noite-da-historia'];
    const sling = registry.quests['tutorial-funda-forjaprata'];

    expect(system.variables[106]).toBe('v_qNoiteDaHistoria_stage');
    expect(system.variables[111]).toBe('v_qTutorialFundaForjaprata_stage');
    expect([...validateGraph(night)].sort((a, b) => a - b)).toEqual([0, 10, 15, 20, 90]);
    expect(night.transitions).toMatchObject({
      START: { from: [0], to: 10 },
      REACH_SEAT: { from: [10], to: 15 },
      COMPLETE_VN: { from: [15], to: 20 },
      ARRIVE_MAP045: { from: [20], to: 90, terminal: true },
    });
    expect(night.pkd.objectives).toEqual([
      { id: 1, knownFrom: 10, completedAt: 15 },
      { id: 2, knownFrom: 15, completedAt: 20 },
    ]);

    expect([...validateGraph(sling)].sort((a, b) => a - b)).toEqual([0, 10, 20, 90]);
    expect(sling.transitions.LEAVE_EQUIPPED).toEqual({
      from: [20],
      to: 90,
      requirements: [],
      effects: [],
      terminal: true,
    });
    expect(sling.pkd.completeQuestAtTerminal).toBe(false);
    expect(sling.pkd.objectives[1]).toEqual({ id: 2, knownFrom: 20, completedAt: null });
  });

  test('rejects an in-memory graph whose new milestone becomes unreachable', () => {
    const broken = structuredClone(registry.quests['noite-da-historia']);
    delete broken.transitions.REACH_SEAT;
    expect(() => validateGraph(broken)).toThrow('terminal 90 is unreachable');
  });

  test('Map022 starts once at E30 and enters the VN only from state 10 at E18', () => {
    const startPage = event(maps[22], 30, 'EX — Noite da História: convocação').pages[0];
    expect(startPage.list[0]).toMatchObject({ code: 111, indent: 0, parameters: [1, 106, 0, 0, 0] });
    expect(startPage.list.filter(command => isPluginCommand(command, 'Coreto_QuestCore', 'QuestTransition', { questKey: 'noite-da-historia', transitionId: 'START' }))).toHaveLength(1);

    const position = event(maps[22], 18, 'EX — Noite da História: posição');
    const entryPage = variablePage(position, 106, 10);
    expect(entryPage.trigger).toBe(1);
    expect(entryPage.list.filter(command => isPluginCommand(command, 'Coreto_QuestCore', 'AssertQuestState', { questKey: 'noite-da-historia', expectedState: '10' }))).toHaveLength(1);
    expect(entryPage.list.filter(command => isPluginCommand(command, 'Coreto_QuestVN', 'EnterVisualNovel', { questKey: 'noite-da-historia', entryKey: 'CENA_PRINCIPAL' }))).toHaveLength(1);
    expect(selectedPage(position, { 106: 20 }).index).toBe(1);
    expect(selectedPage(position, { 106: 90 }).index).toBe(1);
  });

  test('Map046 commits arrival before dialogue and completes the VN from state 15', () => {
    const night = registry.quests['noite-da-historia'];
    expect(night.extensions.questVN).toMatchObject({
      mapId: 46,
      entries: { CENA_PRINCIPAL: { eventId: 1, allowedStates: [10, 15] } },
    });

    const page = event(maps[46], 1, 'VN — Noite da História: diálogo principal').pages[0];
    const assertSession = commandIndex(page, command => isPluginCommand(command, 'Coreto_QuestVN', 'AssertVisualNovelSession', { questKey: 'noite-da-historia', entryKey: 'CENA_PRINCIPAL' }));
    const assertState = commandIndex(page, command => isPluginCommand(command, 'Coreto_QuestCore', 'AssertQuestState', { questKey: 'noite-da-historia', expectedState: '10' }));
    const reachSeat = commandIndex(page, command => isPluginCommand(command, 'Coreto_QuestCore', 'QuestTransition', { questKey: 'noite-da-historia', transitionId: 'REACH_SEAT' }));
    const firstDialogue = commandIndex(page, command => command.code === 101);
    const complete = commandIndex(page, command => isPluginCommand(command, 'Coreto_QuestCore', 'QuestTransition', { questKey: 'noite-da-historia', transitionId: 'COMPLETE_VN' }));
    const finish = commandIndex(page, command => isPluginCommand(command, 'Coreto_QuestVN', 'FinishVisualNovel'));
    const exit = commandIndex(page, command => command.code === 115);

    expect(assertSession).toBeGreaterThanOrEqual(0);
    expect(assertSession).toBeLessThan(assertState);
    expect(assertState).toBeLessThan(reachSeat);
    expect(reachSeat).toBeLessThan(firstDialogue);
    expect(firstDialogue).toBeLessThan(complete);
    expect(complete).toBeLessThan(finish);
    expect(finish).toBeLessThan(exit);
  });

  test('Map045 projects the stadium task through the registry and closes the sling microflow', () => {
    const chest = event(maps[45], 20, 'Bau - Funda');
    const chestPage = variablePage(chest, 111, 10);
    const foundSling = commandIndex(chestPage, command => isPluginCommand(command, 'Coreto_QuestCore', 'QuestTransition', { questKey: 'tutorial-funda-forjaprata', transitionId: 'FOUND_SLING' }));
    const localTerminal = commandIndex(chestPage, command => command.code === 123 && command.parameters?.[0] === 'A' && command.parameters?.[1] === 0);
    expect(foundSling).toBeGreaterThanOrEqual(0);
    expect(foundSling).toBeLessThan(localTerminal);
    expect(JSON.stringify(chestPage.list)).not.toContain('SQSM.ShowTaskForQuest');

    const door = event(maps[45], 7, 'Sair da Casa');
    const state20Page = selectedPage(door, { 111: 20, 34: 0, 35: 0 }).page;
    const leave = commandIndex(state20Page, command => isPluginCommand(command, 'Coreto_QuestCore', 'QuestTransition', { questKey: 'tutorial-funda-forjaprata', transitionId: 'LEAVE_EQUIPPED' }));
    const transfer = commandIndex(state20Page, command => command.code === 201 && JSON.stringify(command.parameters) === JSON.stringify([0, 44, 5, 22, 0, 0]));
    expect(state20Page.list[leave].indent).toBe(4);
    expect(leave).toBeLessThan(transfer);
    expect(state20Page.list[transfer + 1]).toMatchObject({ code: 115, indent: 4 });

    const recovery = variablePage(door, 111, 90);
    expect(selectedPage(door, { 111: 90, 34: 0, 35: 0 }).page).toBe(recovery);
    expect(recovery.list[0]).toMatchObject({ code: 111, indent: 0, parameters: [4, 3, 4, 1] });
    expect(recovery.list).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ code: 201, indent: 1, parameters: [0, 44, 5, 22, 0, 0] }),
        expect.objectContaining({ code: 411, indent: 0 }),
        expect.objectContaining({ code: 412, indent: 0 }),
      ]),
    );
    expect(selectedPage(door, { 111: 90, 34: 12, 35: 0 }).index).toBe(2);
  });

  test('semantic page discovery survives unrelated page reindexing', () => {
    const door = structuredClone(event(maps[45], 7));
    door.pages.unshift(structuredClone(door.pages[0]));
    expect(variablePage(door, 111, 90).conditions.variableValue).toBe(90);
  });

  test('Map049 retains the paired VN session and exact opening state', () => {
    const page = event(maps[49], 1, 'VN - Casa Forjaprata: pesadelo e despertar').pages[0];
    expect(
      page.list.filter(command => isPluginCommand(command, 'Coreto_QuestVN', 'AssertVisualNovelSession', { questKey: 'tutorial-funda-forjaprata', entryKey: 'ABERTURA_FORJAPRATA' })),
    ).toHaveLength(1);
    expect(page.list.filter(command => isPluginCommand(command, 'Coreto_QuestCore', 'AssertQuestState', { questKey: 'tutorial-funda-forjaprata', expectedState: '0' }))).toHaveLength(1);
    expect(page.list.filter(command => isPluginCommand(command, 'Coreto_QuestVN', 'FinishVisualNovel'))).toHaveLength(1);
  });

  test('authorized maps do not write canonical quest variables directly', () => {
    for (const mapData of Object.values(maps)) {
      for (const mapEvent of mapData.events.filter(Boolean)) {
        for (const page of mapEvent.pages) {
          for (const command of page.list) {
            if (command.code === 122) {
              const [startId, endId] = command.parameters;
              expect(startId <= 106 && endId >= 106).toBe(false);
              expect(startId <= 111 && endId >= 111).toBe(false);
            }
            if (command.code === 355 || command.code === 655) {
              const script = String(command.parameters?.[0] ?? '');
              expect(script).not.toMatch(/setValue\s*\(\s*(106|111)\b/);
            }
          }
        }
      }
    }
  });

  test('the current journal pointer targets Map022/E18', () => {
    expect(pkdPointer(parsePluginsConfig(), 'assistirNoiteHistoria', 1)).toEqual([{ mapId: 22, eventId: 18 }]);
  });
});
